#!/bin/sh
cd "$(dirname "$0")"
# This file only makes sense if you have the annotator repository cloned
# to the same directory where you keep dom-text-mapper.
watch -n1 "cp -u -t ../../annotator/lib/vendor ../src/dom_text_matcher.js ../src/dom_text_matcher.map ../src/text_match_engines.js ../src/text_match_engines.map"
