#!/bin/sh
cd "$(dirname "$0")"
# This file only makes sense if you have the annotator repository cloned
# to the same directory where you keep dom-text-matcher.
watch -n1 "cp -u -t ../../annotator/lib/vendor ../src/*.js ../src/*.map; cp -u -t ../../annotator/lib/src ../src/*.coffee"
